/* 
 * IMO® Precision Normalize API
 *
 * <p>IMO® Precision Normalize provides normalization capabilities enabling standardization of inconsistent clinical data from diverse health information systems to a common, clinically validated terminology to ensure that problems, procedures, and medications have clean, enriched, and consistent meanings. This API normalizes input terms or codes to IMO identifiers.</p> <p>The information provided is confidential and proprietary. Any use of this outside an agreement or engagement with IMO is prohibited.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: customersupport@imo-online.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IMO.NormalizeSearch.SDK.Client.OpenAPIDateConverter;

namespace IMO.NormalizeSearch.SDK.Model
{
    /// <summary>
    /// NormalizeResponseResponseMetadataMappingsRxnormCodes
    /// </summary>
    [DataContract]
    public partial class NormalizeResponseResponseMetadataMappingsRxnormCodes :  IEquatable<NormalizeResponseResponseMetadataMappingsRxnormCodes>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizeResponseResponseMetadataMappingsRxnormCodes" /> class.
        /// </summary>
        /// <param name="rxnormCode">An RxNorm code mapped to the IMO lexical.</param>
        /// <param name="rxnormTitles">rxnormTitles.</param>
        public NormalizeResponseResponseMetadataMappingsRxnormCodes(string rxnormCode = default(string), List<NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles> rxnormTitles = default(List<NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles>))
        {
            this.RxnormCode = rxnormCode;
            this.RxnormTitles = rxnormTitles;
        }
        
        /// <summary>
        /// An RxNorm code mapped to the IMO lexical
        /// </summary>
        /// <value>An RxNorm code mapped to the IMO lexical</value>
        [DataMember(Name="rxnorm_code", EmitDefaultValue=false)]
        public string RxnormCode { get; set; }

        /// <summary>
        /// Gets or Sets RxnormTitles
        /// </summary>
        [DataMember(Name="rxnorm_titles", EmitDefaultValue=false)]
        public List<NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles> RxnormTitles { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NormalizeResponseResponseMetadataMappingsRxnormCodes {\n");
            sb.Append("  RxnormCode: ").Append(RxnormCode).Append("\n");
            sb.Append("  RxnormTitles: ").Append(RxnormTitles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NormalizeResponseResponseMetadataMappingsRxnormCodes);
        }

        /// <summary>
        /// Returns true if NormalizeResponseResponseMetadataMappingsRxnormCodes instances are equal
        /// </summary>
        /// <param name="input">Instance of NormalizeResponseResponseMetadataMappingsRxnormCodes to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NormalizeResponseResponseMetadataMappingsRxnormCodes input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RxnormCode == input.RxnormCode ||
                    (this.RxnormCode != null &&
                    this.RxnormCode.Equals(input.RxnormCode))
                ) && 
                (
                    this.RxnormTitles == input.RxnormTitles ||
                    this.RxnormTitles != null &&
                    input.RxnormTitles != null &&
                    this.RxnormTitles.SequenceEqual(input.RxnormTitles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RxnormCode != null)
                    hashCode = hashCode * 59 + this.RxnormCode.GetHashCode();
                if (this.RxnormTitles != null)
                    hashCode = hashCode * 59 + this.RxnormTitles.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
