/* 
 * IMO® Precision Normalize API
 *
 * <p>IMO® Precision Normalize provides normalization capabilities enabling standardization of inconsistent clinical data from diverse health information systems to a common, clinically validated terminology to ensure that problems, procedures, and medications have clean, enriched, and consistent meanings. This API normalizes input terms or codes to IMO identifiers.</p> <p>The information provided is confidential and proprietary. Any use of this outside an agreement or engagement with IMO is prohibited.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: customersupport@imo-online.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IMO.NormalizeSearch.SDK.Client.OpenAPIDateConverter;

namespace IMO.NormalizeSearch.SDK.Model
{
    /// <summary>
    /// NormalizeResponse
    /// </summary>
    [DataContract]
    public partial class NormalizeResponse :  IEquatable<NormalizeResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizeResponse" /> class.
        /// </summary>
        /// <param name="clientRequestId">Unique identifier of the request from the partner application.</param>
        /// <param name="requestId">Unique identifier of the request for internal use.</param>
        /// <param name="preferences">preferences.</param>
        /// <param name="requests">requests.</param>
        /// <param name="responseTime">Time taken in milliseconds to process the entire request.</param>
        public NormalizeResponse(string clientRequestId = default(string), string requestId = default(string), NormalizeResponsePreferences preferences = default(NormalizeResponsePreferences), List<NormalizeResponseRequests> requests = default(List<NormalizeResponseRequests>), decimal responseTime = default(decimal))
        {
            this.ClientRequestId = clientRequestId;
            this.RequestId = requestId;
            this.Preferences = preferences;
            this.Requests = requests;
            this.ResponseTime = responseTime;
        }
        
        /// <summary>
        /// Unique identifier of the request from the partner application
        /// </summary>
        /// <value>Unique identifier of the request from the partner application</value>
        [DataMember(Name="client_request_id", EmitDefaultValue=false)]
        public string ClientRequestId { get; set; }

        /// <summary>
        /// Unique identifier of the request for internal use
        /// </summary>
        /// <value>Unique identifier of the request for internal use</value>
        [DataMember(Name="request_id", EmitDefaultValue=false)]
        public string RequestId { get; set; }

        /// <summary>
        /// Gets or Sets Preferences
        /// </summary>
        [DataMember(Name="preferences", EmitDefaultValue=false)]
        public NormalizeResponsePreferences Preferences { get; set; }

        /// <summary>
        /// Gets or Sets Requests
        /// </summary>
        [DataMember(Name="requests", EmitDefaultValue=false)]
        public List<NormalizeResponseRequests> Requests { get; set; }

        /// <summary>
        /// Time taken in milliseconds to process the entire request
        /// </summary>
        /// <value>Time taken in milliseconds to process the entire request</value>
        [DataMember(Name="response_time", EmitDefaultValue=false)]
        public decimal ResponseTime { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NormalizeResponse {\n");
            sb.Append("  ClientRequestId: ").Append(ClientRequestId).Append("\n");
            sb.Append("  RequestId: ").Append(RequestId).Append("\n");
            sb.Append("  Preferences: ").Append(Preferences).Append("\n");
            sb.Append("  Requests: ").Append(Requests).Append("\n");
            sb.Append("  ResponseTime: ").Append(ResponseTime).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NormalizeResponse);
        }

        /// <summary>
        /// Returns true if NormalizeResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of NormalizeResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NormalizeResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.ClientRequestId == input.ClientRequestId ||
                    (this.ClientRequestId != null &&
                    this.ClientRequestId.Equals(input.ClientRequestId))
                ) && 
                (
                    this.RequestId == input.RequestId ||
                    (this.RequestId != null &&
                    this.RequestId.Equals(input.RequestId))
                ) && 
                (
                    this.Preferences == input.Preferences ||
                    (this.Preferences != null &&
                    this.Preferences.Equals(input.Preferences))
                ) && 
                (
                    this.Requests == input.Requests ||
                    this.Requests != null &&
                    input.Requests != null &&
                    this.Requests.SequenceEqual(input.Requests)
                ) && 
                (
                    this.ResponseTime == input.ResponseTime ||
                    this.ResponseTime.Equals(input.ResponseTime)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.ClientRequestId != null)
                    hashCode = hashCode * 59 + this.ClientRequestId.GetHashCode();
                if (this.RequestId != null)
                    hashCode = hashCode * 59 + this.RequestId.GetHashCode();
                if (this.Preferences != null)
                    hashCode = hashCode * 59 + this.Preferences.GetHashCode();
                if (this.Requests != null)
                    hashCode = hashCode * 59 + this.Requests.GetHashCode();
                hashCode = hashCode * 59 + this.ResponseTime.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
