/* 
 * IMO® Precision Normalize API
 *
 * <p>IMO® Precision Normalize provides normalization capabilities enabling standardization of inconsistent clinical data from diverse health information systems to a common, clinically validated terminology to ensure that problems, procedures, and medications have clean, enriched, and consistent meanings. This API normalizes input terms or codes to IMO identifiers.</p> <p>The information provided is confidential and proprietary. Any use of this outside an agreement or engagement with IMO is prohibited.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: customersupport@imo-online.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IMO.NormalizeSearch.SDK.Client.OpenAPIDateConverter;

namespace IMO.NormalizeSearch.SDK.Model
{
    /// <summary>
    /// NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles
    /// </summary>
    [DataContract]
    public partial class NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles :  IEquatable<NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles" /> class.
        /// </summary>
        /// <param name="title">An RxNorm title for rxnorm_code.</param>
        /// <param name="titleType">The RxNorm term type (TTY) for title.</param>
        /// <param name="titleStatus">Indicates if the title is &#39;current&#39; and in the current RxNorm release or &#39;historical&#39; and no longer included in the current RxNorm release.</param>
        public NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles(string title = default(string), string titleType = default(string), string titleStatus = default(string))
        {
            this.Title = title;
            this.TitleType = titleType;
            this.TitleStatus = titleStatus;
        }
        
        /// <summary>
        /// An RxNorm title for rxnorm_code
        /// </summary>
        /// <value>An RxNorm title for rxnorm_code</value>
        [DataMember(Name="title", EmitDefaultValue=false)]
        public string Title { get; set; }

        /// <summary>
        /// The RxNorm term type (TTY) for title
        /// </summary>
        /// <value>The RxNorm term type (TTY) for title</value>
        [DataMember(Name="title_type", EmitDefaultValue=false)]
        public string TitleType { get; set; }

        /// <summary>
        /// Indicates if the title is &#39;current&#39; and in the current RxNorm release or &#39;historical&#39; and no longer included in the current RxNorm release
        /// </summary>
        /// <value>Indicates if the title is &#39;current&#39; and in the current RxNorm release or &#39;historical&#39; and no longer included in the current RxNorm release</value>
        [DataMember(Name="title_status", EmitDefaultValue=false)]
        public string TitleStatus { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles {\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  TitleType: ").Append(TitleType).Append("\n");
            sb.Append("  TitleStatus: ").Append(TitleStatus).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles);
        }

        /// <summary>
        /// Returns true if NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles instances are equal
        /// </summary>
        /// <param name="input">Instance of NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NormalizeResponseResponseMetadataMappingsRxnormRxnormTitles input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Title == input.Title ||
                    (this.Title != null &&
                    this.Title.Equals(input.Title))
                ) && 
                (
                    this.TitleType == input.TitleType ||
                    (this.TitleType != null &&
                    this.TitleType.Equals(input.TitleType))
                ) && 
                (
                    this.TitleStatus == input.TitleStatus ||
                    (this.TitleStatus != null &&
                    this.TitleStatus.Equals(input.TitleStatus))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Title != null)
                    hashCode = hashCode * 59 + this.Title.GetHashCode();
                if (this.TitleType != null)
                    hashCode = hashCode * 59 + this.TitleType.GetHashCode();
                if (this.TitleStatus != null)
                    hashCode = hashCode * 59 + this.TitleStatus.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
