/* 
 * IMO® Precision Normalize API
 *
 * <p>IMO® Precision Normalize provides normalization capabilities enabling standardization of inconsistent clinical data from diverse health information systems to a common, clinically validated terminology to ensure that problems, procedures, and medications have clean, enriched, and consistent meanings. This API normalizes input terms or codes to IMO identifiers.</p> <p>The information provided is confidential and proprietary. Any use of this outside an agreement or engagement with IMO is prohibited.</p>
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: customersupport@imo-online.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = IMO.NormalizeSearch.SDK.Client.OpenAPIDateConverter;

namespace IMO.NormalizeSearch.SDK.Model
{
    /// <summary>
    /// NormalizeResponsePreferences
    /// </summary>
    [DataContract]
    public partial class NormalizeResponsePreferences :  IEquatable<NormalizeResponsePreferences>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="NormalizeResponsePreferences" /> class.
        /// </summary>
        /// <param name="threshold">The minimum score for the matching. Matching with score lower than the threshold will be dropped..</param>
        /// <param name="matchFieldPref">The input field to match on (input_term, input_code, input_term_first, input_code_first)..</param>
        /// <param name="discrepancyCheck">Check if there are discrepancies between input code and input term..</param>
        /// <param name="distinctField">The desired field to filter by unique results. Defaults to lexical_code when size &gt; 1. Accepts values lexical_code and default_lexical_code..</param>
        /// <param name="size">Number of match results returned. Optional, default to 1, max value is 20..</param>
        /// <param name="debug">Returns IMO Concept details along with IMO Lexical details for debug true and only IMO Lexical code for debug false. Default to false..</param>
        public NormalizeResponsePreferences(decimal threshold = default(decimal), string matchFieldPref = default(string), bool discrepancyCheck = default(bool), string distinctField = default(string), decimal size = default(decimal), bool debug = default(bool))
        {
            this.Threshold = threshold;
            this.MatchFieldPref = matchFieldPref;
            this.DiscrepancyCheck = discrepancyCheck;
            this.DistinctField = distinctField;
            this.Size = size;
            this.Debug = debug;
        }
        
        /// <summary>
        /// The minimum score for the matching. Matching with score lower than the threshold will be dropped.
        /// </summary>
        /// <value>The minimum score for the matching. Matching with score lower than the threshold will be dropped.</value>
        [DataMember(Name="threshold", EmitDefaultValue=false)]
        public decimal Threshold { get; set; }

        /// <summary>
        /// The input field to match on (input_term, input_code, input_term_first, input_code_first).
        /// </summary>
        /// <value>The input field to match on (input_term, input_code, input_term_first, input_code_first).</value>
        [DataMember(Name="match_field_pref", EmitDefaultValue=false)]
        public string MatchFieldPref { get; set; }

        /// <summary>
        /// Check if there are discrepancies between input code and input term.
        /// </summary>
        /// <value>Check if there are discrepancies between input code and input term.</value>
        [DataMember(Name="discrepancy_check", EmitDefaultValue=false)]
        public bool DiscrepancyCheck { get; set; }

        /// <summary>
        /// The desired field to filter by unique results. Defaults to lexical_code when size &gt; 1. Accepts values lexical_code and default_lexical_code.
        /// </summary>
        /// <value>The desired field to filter by unique results. Defaults to lexical_code when size &gt; 1. Accepts values lexical_code and default_lexical_code.</value>
        [DataMember(Name="distinct_field", EmitDefaultValue=false)]
        public string DistinctField { get; set; }

        /// <summary>
        /// Number of match results returned. Optional, default to 1, max value is 20.
        /// </summary>
        /// <value>Number of match results returned. Optional, default to 1, max value is 20.</value>
        [DataMember(Name="size", EmitDefaultValue=false)]
        public decimal Size { get; set; }

        /// <summary>
        /// Returns IMO Concept details along with IMO Lexical details for debug true and only IMO Lexical code for debug false. Default to false.
        /// </summary>
        /// <value>Returns IMO Concept details along with IMO Lexical details for debug true and only IMO Lexical code for debug false. Default to false.</value>
        [DataMember(Name="debug", EmitDefaultValue=false)]
        public bool Debug { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class NormalizeResponsePreferences {\n");
            sb.Append("  Threshold: ").Append(Threshold).Append("\n");
            sb.Append("  MatchFieldPref: ").Append(MatchFieldPref).Append("\n");
            sb.Append("  DiscrepancyCheck: ").Append(DiscrepancyCheck).Append("\n");
            sb.Append("  DistinctField: ").Append(DistinctField).Append("\n");
            sb.Append("  Size: ").Append(Size).Append("\n");
            sb.Append("  Debug: ").Append(Debug).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as NormalizeResponsePreferences);
        }

        /// <summary>
        /// Returns true if NormalizeResponsePreferences instances are equal
        /// </summary>
        /// <param name="input">Instance of NormalizeResponsePreferences to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(NormalizeResponsePreferences input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Threshold == input.Threshold ||
                    this.Threshold.Equals(input.Threshold)
                ) && 
                (
                    this.MatchFieldPref == input.MatchFieldPref ||
                    (this.MatchFieldPref != null &&
                    this.MatchFieldPref.Equals(input.MatchFieldPref))
                ) && 
                (
                    this.DiscrepancyCheck == input.DiscrepancyCheck ||
                    this.DiscrepancyCheck.Equals(input.DiscrepancyCheck)
                ) && 
                (
                    this.DistinctField == input.DistinctField ||
                    (this.DistinctField != null &&
                    this.DistinctField.Equals(input.DistinctField))
                ) && 
                (
                    this.Size == input.Size ||
                    this.Size.Equals(input.Size)
                ) && 
                (
                    this.Debug == input.Debug ||
                    this.Debug.Equals(input.Debug)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Threshold.GetHashCode();
                if (this.MatchFieldPref != null)
                    hashCode = hashCode * 59 + this.MatchFieldPref.GetHashCode();
                hashCode = hashCode * 59 + this.DiscrepancyCheck.GetHashCode();
                if (this.DistinctField != null)
                    hashCode = hashCode * 59 + this.DistinctField.GetHashCode();
                hashCode = hashCode * 59 + this.Size.GetHashCode();
                hashCode = hashCode * 59 + this.Debug.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
