"""
    IMO® Precision Normalize API

    <p>IMO® Precision Normalize provides normalization capabilities enabling standardization of inconsistent clinical data from diverse health information systems to a common, clinically validated terminology to ensure that problems, procedures, and medications have clean, enriched, and consistent meanings. This API normalizes input terms or codes to IMO identifiers.</p> <p>The information provided is confidential and proprietary. Any use of this outside an agreement or engagement with IMO is prohibited.</p>  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Contact: customersupport@imo-online.com
    Generated by: https://openapi-generator.tech
"""


import re  # noqa: F401
import sys  # noqa: F401

from normalizeapiclient.model_utils import (  # noqa: F401
    ApiTypeError,
    ModelComposed,
    ModelNormal,
    ModelSimple,
    cached_property,
    change_keys_js_to_python,
    convert_js_args_to_python_args,
    date,
    datetime,
    file_type,
    none_type,
    validate_get_composed_info,
    OpenApiModel
)
from normalizeapiclient.exceptions import ApiAttributeError


def lazy_import():
    from normalizeapiclient.model.normalize_request_preferences_transformations_inner import NormalizeRequestPreferencesTransformationsInner
    globals()['NormalizeRequestPreferencesTransformationsInner'] = NormalizeRequestPreferencesTransformationsInner


class NormalizeRequestPreferences(ModelNormal):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Attributes:
      allowed_values (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          with a capitalized key describing the allowed value and an allowed
          value. These dicts store the allowed enum values.
      attribute_map (dict): The key is attribute name
          and the value is json key in definition.
      discriminator_value_class_map (dict): A dict to go from the discriminator
          variable value to the discriminator class name.
      validations (dict): The key is the tuple path to the attribute
          and the for var_name this is (var_name,). The value is a dict
          that stores validations for max_length, min_length, max_items,
          min_items, exclusive_maximum, inclusive_maximum, exclusive_minimum,
          inclusive_minimum, and regex.
      additional_properties_type (tuple): A tuple of classes accepted
          as additional properties values.
    """

    allowed_values = {
        ('match_field_pref',): {
            'TERM': "input_term",
            'CODE': "input_code",
            'TERM_FIRST': "input_term_first",
            'CODE_FIRST': "input_code_first",
        },
        ('distinct_field',): {
            'LEXICAL_CODE': "lexical_code",
            'DEFAULT_LEXICAL_CODE': "default_lexical_code",
        },
    }

    validations = {
        ('threshold',): {
            'inclusive_maximum': 1,
            'inclusive_minimum': 0,
        },
        ('size',): {
            'inclusive_maximum': 20,
            'inclusive_minimum': 1,
        },
    }

    @cached_property
    def additional_properties_type():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded
        """
        lazy_import()
        return (bool, date, datetime, dict, float, int, list, str, none_type,)  # noqa: E501

    _nullable = False

    @cached_property
    def openapi_types():
        """
        This must be a method because a model may have properties that are
        of type self, this must run after the class is loaded

        Returns
            openapi_types (dict): The key is attribute name
                and the value is attribute type.
        """
        lazy_import()
        return {
            'threshold': (float,),  # noqa: E501
            'match_field_pref': (str,),  # noqa: E501
            'discrepancy_check': (bool,),  # noqa: E501
            'size': (float,),  # noqa: E501
            'distinct_field': (str,),  # noqa: E501
            'debug': (bool,),  # noqa: E501
            'transformations': ([NormalizeRequestPreferencesTransformationsInner],),  # noqa: E501
        }

    @cached_property
    def discriminator():
        return None


    attribute_map = {
        'threshold': 'threshold',  # noqa: E501
        'match_field_pref': 'match_field_pref',  # noqa: E501
        'discrepancy_check': 'discrepancy_check',  # noqa: E501
        'size': 'size',  # noqa: E501
        'distinct_field': 'distinct_field',  # noqa: E501
        'debug': 'debug',  # noqa: E501
        'transformations': 'transformations',  # noqa: E501
    }

    read_only_vars = {
    }

    _composed_schemas = {}

    @classmethod
    @convert_js_args_to_python_args
    def _from_openapi_data(cls, *args, **kwargs):  # noqa: E501
        """NormalizeRequestPreferences - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            threshold (float): The minimum score for the matching. Matching with score lower than the threshold will be dropped.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            match_field_pref (str): The input field to match on (input_term, input_code, input_term_first, input_code_first). “input_term_first” will try match on input term first, if the match score is below threshold, it will then try match on the input code. “input_code_first” will try match on input code first, if code is not found, it will try match on the input term.. [optional] if omitted the server will use the default value of "input_term_first"  # noqa: E501
            discrepancy_check (bool): Check if there are discrepancies between input code and input term.. [optional] if omitted the server will use the default value of False  # noqa: E501
            size (float): Number of match results returned.. [optional] if omitted the server will use the default value of 1  # noqa: E501
            distinct_field (str): The desired field to filter by unique results.. [optional] if omitted the server will use the default value of "“lexical_code” if size > 1, else null"  # noqa: E501
            debug (bool): Returns IMO Concept details along with IMO Lexical details for debug true and only IMO Lexical code for debug false.. [optional] if omitted the server will use the default value of False  # noqa: E501
            transformations ([NormalizeRequestPreferencesTransformationsInner]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', True)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        self = super(OpenApiModel, cls).__new__(cls)

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
        return self

    required_properties = set([
        '_data_store',
        '_check_type',
        '_spec_property_naming',
        '_path_to_item',
        '_configuration',
        '_visited_composed_classes',
    ])

    @convert_js_args_to_python_args
    def __init__(self, *args, **kwargs):  # noqa: E501
        """NormalizeRequestPreferences - a model defined in OpenAPI

        Keyword Args:
            _check_type (bool): if True, values for parameters in openapi_types
                                will be type checked and a TypeError will be
                                raised if the wrong type is input.
                                Defaults to True
            _path_to_item (tuple/list): This is a list of keys or values to
                                drill down to the model in received_data
                                when deserializing a response
            _spec_property_naming (bool): True if the variable names in the input data
                                are serialized names, as specified in the OpenAPI document.
                                False if the variable names in the input data
                                are pythonic names, e.g. snake case (default)
            _configuration (Configuration): the instance to use when
                                deserializing a file_type parameter.
                                If passed, type conversion is attempted
                                If omitted no type conversion is done.
            _visited_composed_classes (tuple): This stores a tuple of
                                classes that we have traveled through so that
                                if we see that class again we will not use its
                                discriminator again.
                                When traveling through a discriminator, the
                                composed schema that is
                                is traveled through is added to this set.
                                For example if Animal has a discriminator
                                petType and we pass in "Dog", and the class Dog
                                allOf includes Animal, we move through Animal
                                once using the discriminator, and pick Dog.
                                Then in Dog, we will make an instance of the
                                Animal class but this time we won't travel
                                through its discriminator because we passed in
                                _visited_composed_classes = (Animal,)
            threshold (float): The minimum score for the matching. Matching with score lower than the threshold will be dropped.. [optional] if omitted the server will use the default value of 0  # noqa: E501
            match_field_pref (str): The input field to match on (input_term, input_code, input_term_first, input_code_first). “input_term_first” will try match on input term first, if the match score is below threshold, it will then try match on the input code. “input_code_first” will try match on input code first, if code is not found, it will try match on the input term.. [optional] if omitted the server will use the default value of "input_term_first"  # noqa: E501
            discrepancy_check (bool): Check if there are discrepancies between input code and input term.. [optional] if omitted the server will use the default value of False  # noqa: E501
            size (float): Number of match results returned.. [optional] if omitted the server will use the default value of 1  # noqa: E501
            distinct_field (str): The desired field to filter by unique results.. [optional] if omitted the server will use the default value of "“lexical_code” if size > 1, else null"  # noqa: E501
            debug (bool): Returns IMO Concept details along with IMO Lexical details for debug true and only IMO Lexical code for debug false.. [optional] if omitted the server will use the default value of False  # noqa: E501
            transformations ([NormalizeRequestPreferencesTransformationsInner]): [optional]  # noqa: E501
        """

        _check_type = kwargs.pop('_check_type', True)
        _spec_property_naming = kwargs.pop('_spec_property_naming', False)
        _path_to_item = kwargs.pop('_path_to_item', ())
        _configuration = kwargs.pop('_configuration', None)
        _visited_composed_classes = kwargs.pop('_visited_composed_classes', ())

        if args:
            for arg in args:
                if isinstance(arg, dict):
                    kwargs.update(arg)
                else:
                    raise ApiTypeError(
                        "Invalid positional arguments=%s passed to %s. Remove those invalid positional arguments." % (
                            args,
                            self.__class__.__name__,
                        ),
                        path_to_item=_path_to_item,
                        valid_classes=(self.__class__,),
                    )

        self._data_store = {}
        self._check_type = _check_type
        self._spec_property_naming = _spec_property_naming
        self._path_to_item = _path_to_item
        self._configuration = _configuration
        self._visited_composed_classes = _visited_composed_classes + (self.__class__,)

        for var_name, var_value in kwargs.items():
            if var_name not in self.attribute_map and \
                        self._configuration is not None and \
                        self._configuration.discard_unknown_keys and \
                        self.additional_properties_type is None:
                # discard variable.
                continue
            setattr(self, var_name, var_value)
            if var_name in self.read_only_vars:
                raise ApiAttributeError(f"`{var_name}` is a read-only attribute. Use `from_openapi_data` to instantiate "
                                     f"class with read only attributes.")
